## trade 数据

In [3]:
import os
import polars as pl
date = ['2025-12-08']
trade_dir = '/root/autodl-tmp/ETHUSDT/trade'
filename = f'ETHUSDT{date[0]}.csv.gz'
filepath = os.path.join(trade_dir, filename)
trade_tick = pl.read_csv(filepath,n_rows=100000)
trade_tick.head()

shape: (5, 11)
┌───────────┬─────────┬──────┬──────┬───┬────────────┬──────────────┬─────────────────┬─────┐
│ timestamp ┆ symbol  ┆ side ┆ size ┆ … ┆ grossValue ┆ homeNotional ┆ foreignNotional ┆ RPI │
│ ---       ┆ ---     ┆ ---  ┆ ---  ┆   ┆ ---        ┆ ---          ┆ ---             ┆ --- │
│ f64       ┆ str     ┆ str  ┆ f64  ┆   ┆ f64        ┆ f64          ┆ f64             ┆ i64 │
╞═══════════╪═════════╪══════╪══════╪═══╪════════════╪══════════════╪═════════════════╪═════╡
│ 1.7652e9  ┆ ETHUSDT ┆ Buy  ┆ 0.01 ┆ … ┆ 3.0581e9   ┆ 0.01         ┆ 30.5808         ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Sell ┆ 0.92 ┆ … ┆ 2.8134e11  ┆ 0.92         ┆ 2813.4244       ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Sell ┆ 0.05 ┆ … ┆ 1.5290e10  ┆ 0.05         ┆ 152.9035        ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Sell ┆ 0.03 ┆ … ┆ 9.1742e9   ┆ 0.03         ┆ 91.7421         ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Sell ┆ 0.23 ┆ … ┆ 7.0336e10  ┆ 0.23         ┆ 703.3561        ┆ 0   │
└───────────┴─────────┴──────┴──────┴───┴────────────┴──────────────┴─────────────────┴─────┘

In [4]:
trade_tick

shape: (100_000, 11)
┌───────────┬─────────┬──────┬──────┬───┬────────────┬──────────────┬─────────────────┬─────┐
│ timestamp ┆ symbol  ┆ side ┆ size ┆ … ┆ grossValue ┆ homeNotional ┆ foreignNotional ┆ RPI │
│ ---       ┆ ---     ┆ ---  ┆ ---  ┆   ┆ ---        ┆ ---          ┆ ---             ┆ --- │
│ f64       ┆ str     ┆ str  ┆ f64  ┆   ┆ f64        ┆ f64          ┆ f64             ┆ i64 │
╞═══════════╪═════════╪══════╪══════╪═══╪════════════╪══════════════╪═════════════════╪═════╡
│ 1.7652e9  ┆ ETHUSDT ┆ Buy  ┆ 0.01 ┆ … ┆ 3.0581e9   ┆ 0.01         ┆ 30.5808         ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Sell ┆ 0.92 ┆ … ┆ 2.8134e11  ┆ 0.92         ┆ 2813.4244       ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Sell ┆ 0.05 ┆ … ┆ 1.5290e10  ┆ 0.05         ┆ 152.9035        ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Sell ┆ 0.03 ┆ … ┆ 9.1742e9   ┆ 0.03         ┆ 91.7421         ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Sell ┆ 0.23 ┆ … ┆ 7.0336e10  ┆ 0.23         ┆ 703.3561        ┆ 0   │
│ …         ┆ …       ┆ …    ┆ …    ┆ … ┆ …          ┆ …            ┆ …               ┆ …   │
│ 1.7652e9  ┆ ETHUSDT ┆ Buy  ┆ 0.03 ┆ … ┆ 9.1851e9   ┆ 0.03         ┆ 91.8507         ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Buy  ┆ 0.03 ┆ … ┆ 9.1851e9   ┆ 0.03         ┆ 91.8507         ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Buy  ┆ 0.03 ┆ … ┆ 9.1851e9   ┆ 0.03         ┆ 91.8507         ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Buy  ┆ 0.03 ┆ … ┆ 9.1851e9   ┆ 0.03         ┆ 91.8507         ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Buy  ┆ 0.03 ┆ … ┆ 9.1851e9   ┆ 0.03         ┆ 91.8507         ┆ 0   │
└───────────┴─────────┴──────┴──────┴───┴────────────┴──────────────┴─────────────────┴─────┘