## trade 数据

In [3]:
import os
import polars as pl
date = ['2025-12-08']
trade_dir = '/root/autodl-tmp/ETHUSDT/trade'
filename = f'ETHUSDT{date[0]}.csv.gz'
filepath = os.path.join(trade_dir, filename)
trade_tick = pl.read_csv(filepath,n_rows=100000)
trade_tick.head()

shape: (5, 11)
┌───────────┬─────────┬──────┬──────┬───┬────────────┬──────────────┬─────────────────┬─────┐
│ timestamp ┆ symbol  ┆ side ┆ size ┆ … ┆ grossValue ┆ homeNotional ┆ foreignNotional ┆ RPI │
│ ---       ┆ ---     ┆ ---  ┆ ---  ┆   ┆ ---        ┆ ---          ┆ ---             ┆ --- │
│ f64       ┆ str     ┆ str  ┆ f64  ┆   ┆ f64        ┆ f64          ┆ f64             ┆ i64 │
╞═══════════╪═════════╪══════╪══════╪═══╪════════════╪══════════════╪═════════════════╪═════╡
│ 1.7652e9  ┆ ETHUSDT ┆ Buy  ┆ 0.01 ┆ … ┆ 3.0581e9   ┆ 0.01         ┆ 30.5808         ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Sell ┆ 0.92 ┆ … ┆ 2.8134e11  ┆ 0.92         ┆ 2813.4244       ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Sell ┆ 0.05 ┆ … ┆ 1.5290e10  ┆ 0.05         ┆ 152.9035        ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Sell ┆ 0.03 ┆ … ┆ 9.1742e9   ┆ 0.03         ┆ 91.7421         ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Sell ┆ 0.23 ┆ … ┆ 7.0336e10  ┆ 0.23         ┆ 703.3561        ┆ 0   │
└───────────┴─────────┴──────┴──────┴───┴────────────┴──────────────┴─────────────────┴─────┘

In [4]:
trade_tick

shape: (100_000, 11)
┌───────────┬─────────┬──────┬──────┬───┬────────────┬──────────────┬─────────────────┬─────┐
│ timestamp ┆ symbol  ┆ side ┆ size ┆ … ┆ grossValue ┆ homeNotional ┆ foreignNotional ┆ RPI │
│ ---       ┆ ---     ┆ ---  ┆ ---  ┆   ┆ ---        ┆ ---          ┆ ---             ┆ --- │
│ f64       ┆ str     ┆ str  ┆ f64  ┆   ┆ f64        ┆ f64          ┆ f64             ┆ i64 │
╞═══════════╪═════════╪══════╪══════╪═══╪════════════╪══════════════╪═════════════════╪═════╡
│ 1.7652e9  ┆ ETHUSDT ┆ Buy  ┆ 0.01 ┆ … ┆ 3.0581e9   ┆ 0.01         ┆ 30.5808         ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Sell ┆ 0.92 ┆ … ┆ 2.8134e11  ┆ 0.92         ┆ 2813.4244       ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Sell ┆ 0.05 ┆ … ┆ 1.5290e10  ┆ 0.05         ┆ 152.9035        ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Sell ┆ 0.03 ┆ … ┆ 9.1742e9   ┆ 0.03         ┆ 91.7421         ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Sell ┆ 0.23 ┆ … ┆ 7.0336e10  ┆ 0.23         ┆ 703.3561        ┆ 0   │
│ …         ┆ …       ┆ …    ┆ …    ┆ … ┆ …          ┆ …            ┆ …               ┆ …   │
│ 1.7652e9  ┆ ETHUSDT ┆ Buy  ┆ 0.03 ┆ … ┆ 9.1851e9   ┆ 0.03         ┆ 91.8507         ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Buy  ┆ 0.03 ┆ … ┆ 9.1851e9   ┆ 0.03         ┆ 91.8507         ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Buy  ┆ 0.03 ┆ … ┆ 9.1851e9   ┆ 0.03         ┆ 91.8507         ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Buy  ┆ 0.03 ┆ … ┆ 9.1851e9   ┆ 0.03         ┆ 91.8507         ┆ 0   │
│ 1.7652e9  ┆ ETHUSDT ┆ Buy  ┆ 0.03 ┆ … ┆ 9.1851e9   ┆ 0.03         ┆ 91.8507         ┆ 0   │
└───────────┴─────────┴──────┴──────┴───┴────────────┴──────────────┴─────────────────┴─────┘

In [1]:
import torch
import torch.nn.functional as F

# ----------------------
# 1. 构造一个超级简单的测试数据
# ----------------------
# 形状：(B=1, C=1, T=5, F=1) → 批次1，通道1，时间长度5，特征1
x = torch.tensor([[[
    [1.0],   # T=0
    [2.0],   # T=1
    [3.0],   # T=2
    [4.0],   # T=3
    [5.0]    # T=4
]]])

print("【原始输入】shape:", x.shape)
print(x.squeeze().numpy())  # 打印成一维方便看

# ----------------------
# 2. 因果填充：左侧 pad=2 (kernel=3 需要 pad 2个)
# F.pad 参数：(左, 右, 上, 下)
# ----------------------
time_pad = 2  # 时间维度左侧填充 2 个

# 🔥 关键：使用 replicate 模式
x_padded = F.pad(x, (0, 0, time_pad, 0), mode="replicate")

print("\n【Replicate 填充后】shape:", x_padded.shape)
print(x_padded.squeeze().numpy())

libgomp: Invalid value for environment variable OMP_NUM_THREADS

【原始输入】shape: torch.Size([1, 1, 5, 1])
[1. 2. 3. 4. 5.]

【Replicate 填充后】shape: torch.Size([1, 1, 7, 1])
[1. 1. 1. 2. 3. 4. 5.]